name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx-rtd-theme sphinxcontrib-napoleon

      # Step 4: Build Sphinx docs
      - name: Build documentation
        run: |
          cd docs
          make html
          # List the files for debugging
          echo "Contents of _build/html:"
          ls -R _build/html

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          clean: true               # Remove old files before deploying
          commit_message: "Deploy Sphinx docs via GitHub Actions"
